<?xml version="1.0"?>
<robot name="side_wheel" xmlns:xacro="http://www.ros.org/wiki/xacro">

<!-- 
    <xacro:property name="M_PI" value="3.1415926535897931" />
    <xacro:property name="wheel_radius" value="0.05" /> 
    <xacro:property name="wheel_height" value="0.045" /> -->
    <!-- <xacro:property name="wheel_mass" value="2.5" />  -->
    <!-- in kg-->

    <xacro:property name="M_PI_2" value="1.57079632679" />
    <xacro:property name="side_wheel_radius" value="0.0325" /> 
    <xacro:property name="side_wheel_mass" value="0.5" />
    <!-- translate form origin to side_wheel coordinate -->
    <xacro:property name="base_x_base_link_to_side_wheel_origin" value="0.2225" />
    <xacro:property name="base_y_base_link_to_side_wheel_origin" value="0.0" />
    <xacro:property name="base_z_base_link_to_side_wheel_origin" value="-0.0125" />


    <!-- fb: front back, lr: left right, translateX, Y: + -, flipY: rotate along Y -->
    <xacro:macro name="side_wheel" params="fb parent translateX translateY">

        <link name="caster_${fb}_link">
            <visual>
                <origin rpy="${M_PI_2} 0 0" xyz="0.0 0.0 0 "/>
                <geometry>
                <sphere radius="${side_wheel_radius}"/>
                </geometry>
                <material name="Black"/>
            </visual>
            <collision>
                <geometry>
                <sphere radius="${side_wheel_radius}"/>
                </geometry>
                <origin rpy="${M_PI_2} 0 0" xyz="0 0.0 0 "/>
            </collision>
            <inertial>
                <mass value="${side_wheel_mass}"/>
                <origin xyz="0 0 0"/>
                <inertia ixx="0.001" ixy="0.0" ixz="0.0" iyy="0.001" iyz="0.0" izz="0.001"/>
            </inertial>
        </link>


        <joint name="caster_${fb}_joint" type="fixed">
            <parent link="${parent}"/>
            <child link="caster_${fb}_link"/>

            <origin rpy="-${M_PI_2} 0 0" xyz="${translateX * (base_x_base_link_to_side_wheel_origin - side_wheel_radius)} ${translateY * base_y_base_link_to_side_wheel_origin } ${base_z_base_link_to_side_wheel_origin}"/>
        </joint>


        <gazebo reference="caster_${fb}_link">
            <mu1>0.1</mu1>
            <mu2>0.1</mu2>
            <kp>1000000.0</kp>
            <kd>100.0</kd>
            <minDepth>0.001</minDepth>
            <maxVel>1.0</maxVel>
            <material>Gazebo/FlatBlack</material>
        </gazebo>

    </xacro:macro>

    
</robot>