map_update_interval: 5.0 #15.0
maxUrange: 3 #5.0
maxRange: 10.0
minRange: -0.5
sigma: 0.05
kernelSize: 1
lstep: 0.05
astep: 0.05
iterations: 5
lsigma: 0.075
ogain: 3.0
lskip: 0
minimumScore: 80
srr: 0.01 # 0.1
srt: 0.02 # 0.2
str: 0.01 # 0.1
stt: 0.02 # 0.2
linearUpdate: 0.5 #1.0
angularUpdate: 0.436 #0.2
temporalUpdate: -1.0 #0.5
resampleThreshold: 0.5
particles: 80 #100
xmin: -1.0 #-10.0
ymin: -1.0 #-10.0
xmax: 1.0 #10.0
ymax: 1.0 #10.0
delta: 0.05
llsamplerange: 0.01
llsamplestep: 0.01
lasamplerange: 0.005
lasamplestep: 0.005
transform_publish_period: 0.1

